project_name = "async-anthropic"
language = "Rust"

openai_api_key = "env:KWAAK_OPENAI_API_KEY"
#anthropic_api_key = "env:ANTHROPIC_API_KEY"
github_api_key = "env:KWAAK_GITHUB_TOKEN"
tavily_api_key = "env:TAVILY_API_KEY"

[commands]
test = "RUST_BACKTRACE=1 cargo test --no-fail-fast --color=never"
coverage = "cargo llvm-cov nextest --no-clean --summary-only"
# Example: lint_and_fix = "cargo clippy --fix --allow-dirty --allow-staged && cargo fmt"
#lint_and_fix = "<YOUR LINT AND FIX COMMAND>"

[git]
owner = "bosun-ai"
repository = "async-anthropic"
main_branch = "main"
auto_push_remote = true

[llm.indexing]
provider = "OpenAI"
prompt_model = "gpt-4o-mini"

[llm.query]
provider = "OpenAI"
prompt_model = "gpt-4o"

[llm.embedding]
provider = "OpenAI"
embedding_model = "text-embedding-3-large"

[docker]
dockerfile = "Dockerfile"
